/* This file is automatically generated. Do not edit this file. */
import { describe, expect, test } from "vitest";
import { Schema } from "../schema.js";
describe("exclusiveMaximum validation", () => {
  const schema = {
    $schema: "https://json-schema.org/draft/2020-12/schema",
    exclusiveMaximum: 3,
  };
  test("below the exclusiveMaximum is valid", () => {
    const instance = new Schema(schema);
    expect(instance.validate(2.2)).toBeTruthy();
  });
  test("boundary point is invalid", () => {
    const instance = new Schema(schema);
    expect(instance.validate(3)).toBeFalsy();
  });
  test("above the exclusiveMaximum is invalid", () => {
    const instance = new Schema(schema);
    expect(instance.validate(3.5)).toBeFalsy();
  });
  test("ignores non-numbers", () => {
    const instance = new Schema(schema);
    expect(instance.validate("x")).toBeTruthy();
  });
});
