/* This file is automatically generated. Do not edit this file. */
import { describe, expect, test } from "vitest";
import { Schema } from "../schema.js";
describe("validate definition against metaschema", () => {
	const schema = {
		$schema: "https://json-schema.org/draft/2020-12/schema",
		$ref: "https://json-schema.org/draft/2020-12/schema",
	};
	test("valid definition schema", () => {
		const instance = new Schema(schema);
		expect(
			instance.validate({ $defs: { foo: { type: "integer" } } }),
		).toBeTruthy();
	});
	test("invalid definition schema", () => {
		const instance = new Schema(schema);
		expect(instance.validate({ $defs: { foo: { type: 1 } } })).toBeFalsy();
	});
});
