packages:
  - tools/*
  - libs/*
  - apps/*

catalog:
  esbuild: ^0.24.2
  jest-extended: ^4.0.2
  tslib: ^2.8.1
  typescript: ^5.7.3
  vitest: ^3.0.5

onlyBuiltDependencies:
  - '@biomejs/biome'
  - esbuild
