export interface RenderTestModuleOptions {
  runnerImport: string;
  fixtureImport: string;
  source: string;
}

export function renderTestModule({
  runnerImport,
  fixtureImport,
  source,
}: RenderTestModuleOptions): string {
  return [
    "/* This file is automatically generated. Do not edit this file. */",
    `import { runTestFile } from ${JSON.stringify(runnerImport)};`,
    "",
    "await runTestFile(",
    `  ${JSON.stringify(source)},`,
    `  new URL(${JSON.stringify(fixtureImport)}, import.meta.url),`,
    ");",
    "",
  ].join("\n");
}
