import { expect, test } from "vitest";
import { renderTestModule } from "./render-test-module.js";

test("renders a thin fixture-backed test module", () => {
  const source = renderTestModule({
    runnerImport: "../src/run-test-groups.js",
    fixtureImport: "./additional-properties.json",
    source: "additionalProperties.json",
  });

  expect(source).toBe(
    [
      "/* This file is automatically generated. Do not edit this file. */",
      'import { runTestFile } from "../src/run-test-groups.js";',
      "",
      "await runTestFile(",
      '  "additionalProperties.json",',
      '  new URL("./additional-properties.json", import.meta.url),',
      ");",
      "",
    ].join("\n"),
  );
  expect(source).not.toContain("typescript");
});
