name: CI

on: [pull_request]

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        node-version: [24]
        platform:
          - ubuntu-latest

    name: ${{ matrix.platform }} / Node.js ${{ matrix.node-version }}
    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 11.15.0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm run build

      - name: Run lint
        run: |
          pnpm cspell --no-summary --no-progress .
          pnpm biome ci .
          pnpm run check:docs
        timeout-minutes: 1

      - name: Run tests
        # TODO: run only related tests
        run: pnpm vitest --run --exclude "src/generated-tests/**"
        timeout-minutes: 1
